name: pokeapi
description: PokeAPI Package
version: 1.0.3
homepage: "https://github.com/prathanbomb/pokedart"

environment:
    sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.3
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9
