name: pokeapi
description: PokeAPI Package
version: 1.0.2
homepage: "https://github.com/prathanbomb/pokedart"

environment:
    sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.8
